### PR TITLE
🛠 config: add configuration to create custom types

### LINKED ISSUE #25: Override default types
Users should have an option to override the default types by adding/modifying/removing the types according to their project needs.

This will be possible by having a configuration file, say `minimalcommit.config.js` or `.minimalcommitrc`

### PR DESCRIPTION
**Pull request by mafzaldev**
fixes #25 

CHANGELOG:
- added `minimalcommit.config.js`
- placed choices list to config file
- added two custom types: `👷 chore`  and  `🚀 deploy`

### CODE REVIEW

**Comment by mafzaldev** [comment]
@khattakdev 
Can you please review my PR?

**Comment by khattakdev** [comment]
@mafzaldev The `minimalcommit.config.js` should be in the user directory, not in the npm package, similar to the way [Prettier](https://prettier.io/) works.

Also - we are not adding more types to the default list. That will be up to the user to modify them.

**Comment by mafzaldev** [comment]
What are you referring to "user directory"?

**Comment by khattakdev** [comment]
> What are you referring to "user directory"?

The person who will be using this package via `npm install...` should be able to override the types in `minimalcommit.config.js`

**Pull request closed without merging**
